<?php
    include_once('utilities/dbconnect.php');
    include_once('includes/nav.php');
    include_once('includes/banner.php');
    include_once('includes/header.php');
    include_once('includes/content.php');
    include_once('includes/directory.php');
    include_once('includes/footer.php');
?>